### ISSUE TITLE
Creadentials view

### ISSUE THREAD

**Issue by karamba228** [MechaJeter23/OFGPasswordManager#12]
I am working on the credentials list now

Should have a PR tomorrow

**Comment by MechaJeter23** [comment]
Ok, go ahead and keep working on it. What I have to do is create a copy of this project and upload it to a new repository. Because, edm0ra already did the portion you're currently working on.  This repository will contain edm0ra's solution and the new repository will contain your solution to show that you participated. I will send you the link to the new one as soon as I'm done uploading everything.
